Text = 'Text'
Whitespace = 'Whitespace'
Newline = 'Newline'
Error = 'Error'
Other = 'Other'

Keyword = 'Keyword'
Name = 'Name'
Literal = 'Literal'
String = 'String'
Number = 'Number'
Punctuation = 'Punctuation'
Operator = 'Operator'
Comparison = 'Comparison'
Wildcard = 'Wildcard'
Comment = 'Comment'
Assignment = 'Assignment'

Generic = 'Generic'
