language: python
python:
  - 3.6
  - 3.7
install:
  - pip install -r requirements.txt
script:
  - python setup.py lint
  - python setup.py test

# Enable 3.7 properly
matrix:
  include:
    - python: 3.7
      dist: xenial
